from LibraryItem import LibraryItem, Book , TextBook, Magazine

def color_rgb(r, g, b):
    return f"\033[38;2;{r};{g};{b}m"

print(color_rgb(255, 165, 0) + "<========[LibraryItem]========>")
library = LibraryItem("Laptop", "L001")
library.display_info()
print("<=============================>")
print()
print(color_rgb(229, 0, 0) + "<===[CheckOut LibraryItem]===>")
library.check_out()
library.display_info()
print("<============================>")
print()
print(color_rgb(0, 255, 0) + "<====[Return LibraryItem]====>")
library.return_item()
library.display_info()
print("<============================>")
print()

print(color_rgb(255, 165, 0) + "<===========[Book]===========>")
book = Book("Harry Potter", "B001", "J.K. Rowling")
book.set_pages_count(350)
book.display_info()
print("<============================>")
print()
print(color_rgb(229, 0, 0) + "<=======[CheckOut Book]======>")
book.check_out()
book.display_info()
print("<============================>")
print()
print(color_rgb(0, 255, 0) + "<========[Return Book]=======>")
book.return_item()
book.display_info()
print("<============================>")
print()

print(color_rgb(255, 165, 0) + "<=========[TextBook]=========>")
textbook = TextBook("In a range of time", "T001", "Kittikawin", "History", "Highschool")
textbook.set_pages_count(500)
textbook.display_info()
print("<============================>")
print()
print(color_rgb(229, 0, 0) + "<=======[CheckOut TextBook]======>")
textbook.check_out()
textbook.display_info()
print("<============================>")
print()
print(color_rgb(0, 255, 0) + "<========[Return TextBook]=======>")
textbook.return_item()
textbook.display_info()
print("<============================>")
print()

print(color_rgb(255, 165, 0) + "<=========[Magazine]=========>")
mag = Magazine("TIME", "M001", 202)
mag.display_info()
print("<============================>")
print(color_rgb(229, 0, 0) + "<=======[CheckOut Magazine]======>")
mag.check_out()
mag.display_info()
print("<============================>")
print()
print(color_rgb(0, 255, 0) + "<========[Return Magazine]=======>")
mag.return_item()
mag.display_info()
print("<============================>\033[0m")


